// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe4_PZptt6e1b-oYTju_Zt7AYFF3YOqCQ',
    appId: '1:115960016787:android:535e50f44a1c9ce5270266',
    messagingSenderId: '115960016787',
    projectId: 'questora-8da3a',
    storageBucket: 'questora-8da3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSjnOLLDwwrKUbRlQ3SVfvDEthsSPOx8A',
    appId: '1:115960016787:ios:97ac4b73705fcd3b270266',
    messagingSenderId: '115960016787',
    projectId: 'questora-8da3a',
    storageBucket: 'questora-8da3a.firebasestorage.app',
    iosClientId: '115960016787-30eo4gqipf7avrp8nstdeijo2r7gn8bo.apps.googleusercontent.com',
    iosBundleId: 'com.example.quest',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXPNLItys5amDiRV3r_5Q7zRIIBjkkBJo',
    appId: '1:115960016787:web:d74269cd213d9eef270266',
    messagingSenderId: '115960016787',
    projectId: 'questora-8da3a',
    authDomain: 'questora-8da3a.firebaseapp.com',
    storageBucket: 'questora-8da3a.firebasestorage.app',
    measurementId: 'G-MH6K2ZCC9G',
  );

}